const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("petdesk", {
  getState: () => ipcRenderer.invoke("state:get"),
  replaceState: (state) => ipcRenderer.invoke("state:replace", state),
  openPanel: () => ipcRenderer.invoke("panel:open"),
  petAction: (action) => ipcRenderer.invoke("pet:action", action),
  rewardCompanion: (reason) => ipcRenderer.invoke("pet:reward", reason),
  petDrag: (payload) => ipcRenderer.send("pet:drag", payload),
  roamPet: (distance) => ipcRenderer.invoke("pet:roam", distance),
  setPetVisibility: (visible) => ipcRenderer.invoke("pet:visibility", visible),
  togglePet: () => ipcRenderer.invoke("pet:toggle"),
  quit: () => ipcRenderer.invoke("app:quit"),
  startFocus: (seconds) => ipcRenderer.invoke("focus:start", seconds),
  pauseFocus: () => ipcRenderer.invoke("focus:pause"),
  completeFocus: () => ipcRenderer.invoke("focus:complete"),
  pickImage: () => ipcRenderer.invoke("image:pick"),
  saveCustomImage: (data) => ipcRenderer.invoke("image:save-custom", data),
  aiTransform: (data) => ipcRenderer.invoke("image:ai-transform", data),
  generateActionPack: (data) => ipcRenderer.invoke("image:generate-action-pack", data),
  deleteCustomPet: (id) => ipcRenderer.invoke("image:delete-custom", id),
  getCustomPetActions: (id) => ipcRenderer.invoke("image:get-custom-actions", id),
  getAiConfig: () => ipcRenderer.invoke("ai:get-config"),
  saveAiConfig: (data) => ipcRenderer.invoke("ai:save-config", data),
  testAiConfig: () => ipcRenderer.invoke("ai:test-config"),
  clearAiConfig: () => ipcRenderer.invoke("ai:clear-config"),
  setStartup: (enabled) => ipcRenderer.invoke("settings:startup", enabled),
  loadWeather: (query) => ipcRenderer.invoke("weather:load", query),
  onState: (callback) => ipcRenderer.on("state:changed", (_, state) => callback(state)),
  onPetAction: (callback) => ipcRenderer.on("pet:action", (_, action) => callback(action)),
  onPetSpeak: (callback) => ipcRenderer.on("pet:speak", (_, payload) => callback(payload)),
  onCompanionReward: (callback) => ipcRenderer.on("pet:rewarded", (_, reward) => callback(reward)),
  onActionPackProgress: (callback) => ipcRenderer.on("image:action-pack-progress", (_, progress) => callback(progress)),
});
